spring:
  application:
    name: wei-kafka-streams-aggregate-sample
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: adornment_added
        process-in-1:
          destination: adornment_deleted
        process-in-2:
          destination: provider_account_linked
        process-in-3:
          destination: provider_account_unlinked
        process-out-0:
          destination: braze_event
      kafka:
        streams:
          binder:
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
              commit.interval.ms: 1000
            serdeError: logAndContinue
          bindings:
            process-in-0:
              consumer:
                configuration:
                  spring.json.value.default.type: kafka.streams.table.join.TileAdded
            process-in-1:
              consumer:
                configuration:
                  spring.json.value.default.type: kafka.streams.table.join.TileRemoved
            process-in-2:
              consumer:
                configuration:
                  spring.json.value.default.type: kafka.streams.table.join.AccountLinked
            process-in-3:
              consumer:
                configuration:
                  spring.json.value.default.type: kafka.streams.table.join.AccountUnlinked
window.size: 30000
