spring:
  kafka:
    bootstrapServers: localhost:9092
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        proto1:
          destination: testtock-proto1
        output:
          destination: xformed-proto1
      kafka:
         binder:
           producer-properties:
             key.serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
             value.serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
             schema.registry.url: http://localhost:8081
           consumer-properties:
             key.deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
             value.deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
             schema.registry.url: http://localhost:8081
             specific.protobuf.value.type: com.life360.gpi.schema.proto$Message
             auto.offset.reset: earliest
payload: none
