spring:
  cloud:
    stream:
      bindings:
        sample-source:
          destination: testtock
        input:
          destination: testtock
        output:
          destination: xformed
payload: json
